name: Generate REAME for GDSC

on: [ workflow_dispatch ]

permissions: 
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-lates
    steps:
      - users: actions/checkout@v3 # checks out the repository contents
      - run: |
        echo "# Hello GDSC" > README.md
        echo "## Generate using ${{github.event.workflow}}" >> README.md
      - uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          default_author: github_actions
          message: "generate README.md"
